apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: hashicorp-vault-api-static-secret
  namespace: hashicorp-vault-api
spec:
  vaultAuthRef: hashicorp-vault-api-static-auth
  namespace: hashicorp-vault-api
  mount: kv-v2
  type: kv-v2
  path: demo-app/config
  refreshAfter: 10s
  destination:
    create: true
    name: config
  rolloutRestartTargets:
  - kind: Deployment
    name: hashicorp-vault-api
