apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\chenyard\AppData\Local\Microsoft\WinGet\Links\kompose.exe -f docker-compose.yml -f docker-compose.override.yml -o deploy/ convert
  labels:
    app.kubernetes.io/instance: hashicorp-vault-api
    app.kubernetes.io/name: hashicorp-vault-api
  name: hashicorp-vault-api-service
  namespace: hashicorp-vault-api
spec:
  selector:
    app.kubernetes.io/name: hashicorp-vault-api
  ports:
    - name: "9030"
      port: 9030
      targetPort: 9030
